# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('time_upload', models.DateTimeField(auto_now_add=True)),
                ('album', models.CharField(max_length=100)),
                ('lyric', models.TextField()),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('metal', 'Metal'), ('islamic', 'Islamic'), ('rnb', 'RnB'), ('campursari', 'Campursari'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('dangdut', 'Dangdut')], max_length=100)),
                ('cover', models.ImageField(default='cover.jpg', upload_to='images/')),
                ('audio', models.FileField(default='songs/tulus.mp3', upload_to='songs/')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
    ]
