# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20191013_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Lagu', 'verbose_name_plural': 'songs'},
        ),
    ]
