# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20191013_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'song', 'verbose_name_plural': 'Soundcloud'},
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, default='tulus.mp3', upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, default='cover.jpeg', upload_to='images/'),
        ),
    ]
