# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_auto_20191021_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, default='songs/tulus.mp3', upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, default='images/cover.jpeg', upload_to='images/'),
        ),
    ]
