# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 18:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0012_auto_20191021_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
