# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='judul', max_length=100),
            preserve_default=False,
        ),
    ]
