# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='album lagu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='songs/tulus.mp3', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('metal', 'Metal'), ('islamic', 'Islamic'), ('rnb', 'RnB'), ('campursari', 'Campursari'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('dangdut', 'Dangdut')], default='genre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.TextField(default='ini lyric guys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default='penyanyiku', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='song',
            name='time_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='judul lagu', max_length=100),
            preserve_default=False,
        ),
    ]
