# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191013_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='song',
        ),
    ]
