# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='isi blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='images/cover.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
