# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191022_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(choices=[('sandy', 'Rahmad Sandy Kurnia'), ('lila', 'Lailatul Murtafiah'), ('neima', 'Annisa Neima Kurnia')], default='neima', max_length=100),
        ),
    ]
