# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-23 11:56
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191022_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
