# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/thumbnail.jpeg', upload_to='images/'),
        ),
    ]
