# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20191014_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/thumbnail.jpeg', upload_to='images/'),
        ),
    ]
