# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20191014_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'Movies'},
        ),
    ]
