# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20191016_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('drama', 'Drama'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('mystery', 'Mistery'), ('action', 'Action'), ('animation', 'Annimation'), ('advanture', 'Advanture'), ('horror', 'Horror'), ('war', 'War'), ('documentary', 'Documentary'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('biography', 'Biography'), ('musical', 'Musical'), ('western', 'Western'), ('game', 'Game'), ('adult', 'Adult'), ('short', 'Short'), ('talk-show', 'Talk-Show')], default='drama', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='director',
            field=models.CharField(blank=True, default='Frank Darabont', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='writers',
            field=models.CharField(blank=True, default='Stephen King', max_length=200),
        ),
    ]
