# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20191020_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('mystery', 'Mistery'), ('action', 'Action'), ('animation', 'Annimation'), ('advanture', 'Advanture'), ('horror', 'Horror'), ('war', 'War'), ('documentary', 'Documentary'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('biography', 'Biography'), ('musical', 'Musical'), ('western', 'Western'), ('game', 'Game'), ('adult', 'Adult'), ('short', 'Short'), ('talk-show', 'Talk-Show')], max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
